version: '3.6'

services:

  mysql:
    container_name: example_mysql
    image: mysql:5.7
    ports:
      - 3306
    restart: always
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./docker/mysql/data.sql:/docker-entrypoint-initdb.d/data.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: example_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  rabbitmq_exporter:
    image: kbudde/rabbitmq-exporter
    container_name: example_rabbitmq-exporter
    depends_on:
      - rabbitmq
    ports:
      - "9999:9090"
    environment:
      RABBIT_URL: "http://rabbitmq:15672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      PUBLISH_PORT: "9090"
      OUTPUT_FORMAT: "JSON"
      LOG_LEVEL: "info"

  php:
    container_name: example_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    user: "$UID"
    volumes:
      - ./:/usr/src/app
    tty: true

  php-fpm:
    container_name: example_php-fpm
    build:
      context: ./docker/php-fpm
    user: "$UID"
    volumes:
      - ./:/var/www/example

  nginx:
    container_name: example_nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/example
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
      - rabbitmq
      - mysql
      - redis
    ports:
      - "80:80"

  prometheus:
    image: prom/prometheus
    container_name: example_prometheus
    depends_on:
      - nginx
      - rabbitmq_exporter
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: example_grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./docker/grafana/config.monitoring
    restart: always

  redis:
    image: redis
    container_name: example_redis
    ports:
      - 63790:6379

volumes:
  grafana_data:
